services:
  - type: web
    name: erp-ai
    env: node
    plan: starter
    region: oregon
    buildCommand: npm run build:render
    startCommand: npm run start
    healthCheckPath: /api/test-db

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

    buildFilter:
      paths:
        - app/**
        - components/**
        - contexts/**
        - hooks/**
        - lib/**
        - prisma/**
        - public/**
        - scripts/**
        - next.config.js
        - package.json
        - package-lock.json
        - tsconfig.json
        - tailwind.config.ts
        - postcss.config.js
        - middleware.ts
        - .env.example

    # Auto-deploy settings
    autoDeploy: true

    # Resource limits
    disk:
      name: erp-ai-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
